### ISSUE TITLE
Map is not showing in Release build

### ISSUE THREAD

**Issue by yashwantkumargaurav** [IbrahimTabba/custom_map_markers#1]
@IbrahimTabba  works fine with my debug build though

**Comment by yashwantkumargaurav** [comment]
Set<Marker>? markers are null in the release build @IbrahimTabba

**Comment by azharul-islam** [comment]
The markers remain null in release build and map never loads. Any luck anyone else?

**Comment by IbrahimTabba** [comment]
@yashwantkumargaurav @azharul-islam 
Thank you guys for reporting the issue.
I'm on it, will let you know once it is fixed.

**Comment by IbrahimTabba** [comment]
@yashwantkumargaurav @azharul-islam 
please upgrade to version 0.0.2 of the package 
the issue was fixed.
